name: 'bookshop_dbt'
version: '1.0.0'
config-version: 2

profile: 'bookshop_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  bookshop_dbt:
    stagging:
      +schema: STAGGING
      +materialized: table
    warehouse:
      +schema: WAREHOUSE
      +materialized: table
    marts:
      +schema: MARTS
      +materialized: table
